/**
 * app/artikel/_lib/artikelIndex.ts
 *
 * Data indeks seluruh artikel ID — satu sumber untuk halaman /artikel
 * (kartu + ItemList schema) dan /feed.xml (RSS). Menambah artikel baru:
 * tambah entri di sini (kategori hanya Panduan/Strategi/Review/Edukasi).
 */

export type Kategori = "Panduan" | "Strategi" | "Review" | "Edukasi";

export interface Artikel {
  slug:      string;
  judul:     string;
  ringkasan: string;
  kategori:  Kategori;
  tanggal:   string;
  menit:     number;
}

export const ARTIKEL: Artikel[] = [
  {
    slug:      "pajak-trading-binary-option",
    judul:     "Pajak Trading Binary Option di Indonesia: Panduan Lapor SPT 2026",
    ringkasan: "Profit trading adalah objek pajak penghasilan. Status pajaknya, tarif PPh progresif 5–35%, contoh hitungan, data yang perlu dicatat, dan langkah lapor SPT Tahunan — dijelaskan sederhana.",
    kategori:  "Edukasi",
    tanggal:   "9 Juli 2026",
    menit:     8,
  },
  {
    slug:      "berapa-penghasilan-trading-binary-option",
    judul:     "Berapa Penghasilan Trading Binary Option? Hitungan Realistis 2026",
    ringkasan: "Matematika jujur tanpa hype: payout 80%, break even di win rate 56%, simulasi 100 order per win rate, peran modal, dan kenapa 'gaji tetap dari trading' itu mitos.",
    kategori:  "Edukasi",
    tanggal:   "9 Juli 2026",
    menit:     9,
  },
  {
    slug:      "withdraw-stockity-pending",
    judul:     "Withdraw Stockity Pending? 7 Penyebab & Cara Mengatasinya 2026",
    ringkasan: "Penarikan lama diproses atau ditolak? 7 penyebab paling umum — KYC belum selesai, turnover bonus, beda nama rekening — plus langkah penyelesaian berurutan dan kapan harus hubungi support.",
    kategori:  "Panduan",
    tanggal:   "9 Juli 2026",
    menit:     7,
  },
  {
    slug:      "deposit-stockity-tidak-masuk",
    judul:     "Deposit Stockity Tidak Masuk? 6 Penyebab & Solusinya 2026",
    ringkasan: "Sudah transfer tapi saldo belum bertambah? Diagnosis berurutan: VA kedaluwarsa, nominal tidak persis, delay gateway — beserta solusi dan bekal klaim ke support agar cepat ditelusuri.",
    kategori:  "Panduan",
    tanggal:   "9 Juli 2026",
    menit:     6,
  },
  {
    slug:      "trading-gold-stockity",
    judul:     "Trading Gold (XAU/USD) di Stockity: Karakter, Jam & Strategi 2026",
    ringkasan: "Deep-dive aset Gold: temperamen safe haven, jam paling likuid dalam WIB (19.00–23.00), berita yang menggerakkannya, strategi pantulan level, dan setting STC AutoTrade khusus emas.",
    kategori:  "Strategi",
    tanggal:   "9 Juli 2026",
    menit:     8,
  },
  {
    slug:      "trading-bitcoin-stockity",
    judul:     "Trading Bitcoin di Stockity: Panduan Crypto 24/7 & Strateginya 2026",
    ringkasan: "Satu-satunya aset yang buka 24/7 termasuk akhir pekan dengan harga pasar riil. Karakter volatilitas BTC, peta waktu WIB, strategi per rezim pasar, dan setting bot yang konservatif.",
    kategori:  "Strategi",
    tanggal:   "9 Juli 2026",
    menit:     8,
  },
  {
    slug:      "stockity-vs-quotex",
    judul:     "Stockity vs Quotex: Perbandingan Lengkap, Mana Lebih Baik? 2026",
    ringkasan: "Perbandingan jujur 8 aspek: minimal deposit, payout, aset, pembayaran lokal Indonesia, kemudahan withdraw, hingga dukungan trading otomatis. Pilih berdasarkan fakta.",
    kategori:  "Review",
    tanggal:   "4 Juli 2026",
    menit:     8,
  },
  {
    slug:      "robot-trading-terbaik-indonesia",
    judul:     "Cara Memilih Robot Trading Terbaik: 7 Kriteria & Red Flags 2026",
    ringkasan: "Kerangka menilai robot trading apapun: 7 kriteria wajib (demo, manajemen risiko, transparansi), 6 tanda bahaya penipuan, dan protokol uji 14 hari sebelum percaya.",
    kategori:  "Review",
    tanggal:   "4 Juli 2026",
    menit:     8,
  },
  {
    slug:      "bonus-deposit-stockity",
    judul:     "Bonus Deposit Stockity: Cara Klaim, Syarat & Jebakannya 2026",
    ringkasan: "Jenis bonus & kode promo Stockity, cara klaim saat deposit, memahami syarat turnover sebelum withdraw, dan kapan bonus justru sebaiknya dilewati.",
    kategori:  "Panduan",
    tanggal:   "4 Juli 2026",
    menit:     6,
  },
  {
    slug:      "turnamen-stockity",
    judul:     "Turnamen Stockity: Cara Ikut, Jenis Kompetisi & Tips Menang 2026",
    ringkasan: "Turnamen gratis & berbayar, cara daftar, sistem leaderboard, hadiah, dan kenapa strategi turnamen harus berbeda total dari trading harian di akun utama.",
    kategori:  "Panduan",
    tanggal:   "4 Juli 2026",
    menit:     6,
  },
  {
    slug:      "stc-autotrade-vs-trading-manual",
    judul:     "Bot Trading vs Trading Manual: Perbandingan Jujur untuk Trader Stockity",
    ringkasan: "Peta jujur 8 aspek: di mana otomasi menang telak, di mana manusia tak tergantikan, dan model hybrid yang dipakai trader berpengalaman.",
    kategori:  "Review",
    tanggal:   "4 Juli 2026",
    menit:     7,
  },
  {
    slug:      "manajemen-modal-trading-binary-option",
    judul:     "Manajemen Modal Trading Binary Option: Aturan 1–5% & Position Sizing",
    ringkasan: "Money management dengan angka: aturan 1–5% per order, tabel ketahanan modal terhadap losing streak, hitungan risiko martingale, dan cara menjalankannya otomatis.",
    kategori:  "Strategi",
    tanggal:   "4 Juli 2026",
    menit:     8,
  },
  {
    slug:      "psikologi-trading-binary-option",
    judul:     "Psikologi Trading Binary Option: 5 Jebakan Emosi & Cara Melawannya",
    ringkasan: "Revenge trading, FOMO, overtrading, overconfidence, loss aversion — kenapa terasa rasional saat terjadi, dan struktur praktis untuk melawannya termasuk otomasi.",
    kategori:  "Edukasi",
    tanggal:   "4 Juli 2026",
    menit:     8,
  },
  {
    slug:      "support-resistance-binary-option",
    judul:     "Support & Resistance Binary Option: Cara Menentukan & Trading di Level",
    ringkasan: "Cara menandai level yang benar-benar valid, strategi bounce vs breakout, kombinasi dengan candlestick & indikator, plus kesalahan pemula paling umum.",
    kategori:  "Edukasi",
    tanggal:   "4 Juli 2026",
    menit:     8,
  },
  {
    slug:      "kalender-ekonomi-binary-option",
    judul:     "Kalender Ekonomi untuk Binary Option: Kapan Trading, Kapan Menghindar",
    ringkasan: "Berita berdampak tinggi (FOMC, NFP, CPI) dan jam rilisnya dalam WIB, efek spike ke strategi teknikal, dan aturan jeda ±30 menit sebelum-sesudah rilis.",
    kategori:  "Strategi",
    tanggal:   "4 Juli 2026",
    menit:     7,
  },
  {
    slug:      "trading-otc-stockity-akhir-pekan",
    judul:     "Trading OTC Stockity di Akhir Pekan: Cara Kerja, Risiko & Tips 2026",
    ringkasan: "Dari mana harga OTC berasal, bedanya dengan pasar reguler, kenapa strategi hari kerja tidak otomatis berlaku, dan cara mengujinya dengan aman di akhir pekan.",
    kategori:  "Edukasi",
    tanggal:   "4 Juli 2026",
    menit:     6,
  },
  {
    slug:      "cara-verifikasi-akun-stockity",
    judul:     "Cara Verifikasi Akun Stockity (KYC): Panduan Lengkap & Syarat 2026",
    ringkasan: "Dokumen yang dibutuhkan, langkah upload yang benar, berapa lama prosesnya, penyebab verifikasi ditolak, dan kenapa KYC wajib diselesaikan sebelum withdraw.",
    kategori:  "Panduan",
    tanggal:   "4 Juli 2026",
    menit:     6,
  },
  {
    slug:      "stockity-tidak-bisa-login",
    judul:     "Stockity Tidak Bisa Login? 7 Penyebab & Cara Mengatasinya 2026",
    ringkasan: "Checklist troubleshooting gagal login Stockity: password & metode login, gangguan jaringan/ISP, server down, cache aplikasi, hingga akun diblokir — beserta solusi tiap kasus.",
    kategori:  "Panduan",
    tanggal:   "4 Juli 2026",
    menit:     7,
  },
  {
    slug:      "cara-main-stockity-pemula",
    judul:     "Cara Main Stockity untuk Pemula: Panduan Lengkap dari Nol 2026",
    ringkasan: "Panduan lengkap bermain Stockity untuk pemula — daftar akun, memahami antarmuka trading, order pertama di mode demo, kesalahan umum, hingga trading otomatis dengan robot.",
    kategori:  "Panduan",
    tanggal:   "3 Juli 2026",
    menit:     9,
  },
  {
    slug:      "akun-demo-stockity",
    judul:     "Akun Demo Stockity: Cara Daftar & Latihan Gratis Tanpa Modal 2026",
    ringkasan: "Cara mengaktifkan akun demo Stockity dengan saldo virtual gratis, perbedaan demo vs real, dan program latihan 7 hari terstruktur sebelum pindah ke akun real.",
    kategori:  "Panduan",
    tanggal:   "3 Juli 2026",
    menit:     7,
  },
  {
    slug:      "jam-trading-terbaik-stockity",
    judul:     "Jam Trading Terbaik Stockity: Waktu Paling Profit (WIB) 2026",
    ringkasan: "Pembagian sesi pasar Asia, Eropa, dan Amerika dalam WIB — jam paling likuid untuk trading di Stockity, waktu yang harus dihindari, dan cara mengotomatiskan jadwal.",
    kategori:  "Strategi",
    tanggal:   "3 Juli 2026",
    menit:     8,
  },
  {
    slug:      "ai-trading-stockity",
    judul:     "AI Trading Stockity: Cara Kerja Robot AI untuk Binary Option 2026",
    ringkasan: "Bagaimana sinyal AI dihasilkan, kapan AI unggul dibanding analisis manual, batasan yang wajib dipahami, dan panduan menggunakan mode AI Signal di STC AutoTrade.",
    kategori:  "Edukasi",
    tanggal:   "3 Juli 2026",
    menit:     8,
  },
  {
    slug:      "robot-trading-stockity",
    judul:     "Robot Trading Stockity: Panduan Lengkap Auto Trade 2026",
    ringkasan: "Panduan lengkap cara kerja robot trading Stockity, 6 mode strategi yang tersedia, manajemen risiko otomatis, dan cara mengaktifkan bot di akun Stockity.id.",
    kategori:  "Panduan",
    tanggal:   "21 Mei 2025",
    menit:     8,
  },
  {
    slug:      "auto-trade-stockity-gratis",
    judul:     "Auto Trade Stockity Gratis: Download Robot Stockity Terbaik 2026",
    ringkasan: "Cara mendapatkan robot trading Stockity secara gratis lewat STC AutoTrade — download APK Android atau akses versi web, lengkap dengan panduan aktivasi.",
    kategori:  "Panduan",
    tanggal:   "21 Mei 2025",
    menit:     6,
  },
  {
    slug:      "cara-setting-robot-stockity",
    judul:     "Cara Setting Robot Trading Stockity: Panduan Konfigurasi Bot 2026",
    ringkasan: "Panduan langkah demi langkah cara setting robot Stockity — konfigurasi martingale, stop loss, stop profit, pilih aset, dan aktifkan bot untuk trading otomatis.",
    kategori:  "Panduan",
    tanggal:   "21 Mei 2025",
    menit:     10,
  },
  {
    slug:      "robot-stockity-android",
    judul:     "Robot Stockity Android: Download APK Bot Trading Terbaik 2026",
    ringkasan: "Panduan download dan instal robot trading Stockity di Android — APK STC AutoTrade, persyaratan perangkat, izin instalasi, dan langkah pertama setelah instal.",
    kategori:  "Panduan",
    tanggal:   "21 Mei 2025",
    menit:     7,
  },
  {
    slug:      "cara-daftar-stockity",
    judul:     "Cara Daftar Stockity: Panduan Registrasi Akun & Mulai Trading 2026",
    ringkasan: "Langkah demi langkah cara daftar akun Stockity.id — dari registrasi, verifikasi email, deposit pertama, hingga menghubungkan akun ke robot STC AutoTrade.",
    kategori:  "Panduan",
    tanggal:   "21 Mei 2025",
    menit:     6,
  },
  {
    slug:      "sinyal-trading-stockity-gratis",
    judul:     "Sinyal Trading Stockity Gratis: CTC, AI Signal & Bot 2026",
    ringkasan: "Panduan mendapatkan sinyal trading Stockity gratis — cara kerja CTC Copy Trading, AI Signal, sinyal indikator, dan cara menggunakannya dengan robot otomatis.",
    kategori:  "Panduan",
    tanggal:   "1 Jun 2025",
    menit:     7,
  },
  {
    slug:      "cara-withdraw-stockity",
    judul:     "Cara Withdraw Stockity: Panduan Tarik Dana ke Rekening 2026",
    ringkasan: "Panduan lengkap cara withdraw Stockity — metode penarikan, minimum saldo, durasi proses, penyebab withdraw gagal, dan tips agar tarik dana berjalan lancar.",
    kategori:  "Panduan",
    tanggal:   "1 Jun 2025",
    menit:     8,
  },
  {
    slug:      "robot-trading-ios-iphone",
    judul:     "Robot Trading iPhone Stockity: Auto Trade di iOS Tanpa Instalasi 2026",
    ringkasan: "Panduan menggunakan robot trading Stockity di iPhone dan iPad — akses STC AutoTrade versi web di Safari tanpa instalasi APK, dengan fitur lengkap dan tips optimasi iOS.",
    kategori:  "Panduan",
    tanggal:   "1 Jun 2025",
    menit:     6,
  },
  {
    slug:      "cara-profit-trading-stockity",
    judul:     "Cara Profit Trading Stockity: Strategi & Tips Konsisten 2026",
    ringkasan: "Strategi, tips, dan sistem manajemen risiko untuk trading konsisten dan profitable di Stockity.id menggunakan robot STC AutoTrade.",
    kategori:  "Strategi",
    tanggal:   "21 Mei 2025",
    menit:     9,
  },
  {
    slug:      "modal-trading-stockity",
    judul:     "Modal Trading Stockity: Berapa Minimum & Cara Mulai Modal Kecil 2026",
    ringkasan: "Berapa modal minimum untuk trading Stockity otomatis? Panduan lengkap kalkulasi modal, manajemen risiko bertahap, dan cara memulai dari modal kecil dengan aman.",
    kategori:  "Strategi",
    tanggal:   "21 Mei 2025",
    menit:     7,
  },
  {
    slug:      "strategi-martingale-stockity",
    judul:     "Strategi Martingale Stockity: Panduan Setting Aman & Efektif 2026",
    ringkasan: "Panduan lengkap strategi martingale di Stockity — cara kerja, tabel kalkulator step & modal, multiplier aman, risiko, dan alternatif anti-martingale.",
    kategori:  "Strategi",
    tanggal:   "1 Jun 2025",
    menit:     10,
  },
  {
    slug:      "trading-binary-option-indonesia",
    judul:     "Trading Binary Option Indonesia: Panduan Lengkap untuk Pemula 2026",
    ringkasan: "Panduan lengkap trading binary option di Indonesia — apa itu binary option, cara kerja, platform terbaik, risiko nyata, dan cara mulai dengan robot trading otomatis.",
    kategori:  "Panduan",
    tanggal:   "1 Jun 2025",
    menit:     10,
  },
  {
    slug:      "stockity-aman-atau-penipuan",
    judul:     "Stockity Aman atau Penipuan? Review Jujur & Faktual 2026",
    ringkasan: "Ulasan jujur Stockity.id — keamanan platform, risiko nyata, bukti withdraw, dan analisis apakah Stockity terpercaya untuk trading binary option.",
    kategori:  "Review",
    tanggal:   "21 Mei 2025",
    menit:     11,
  },
  {
    slug:      "stockity-vs-binomo-vs-olymp-trade",
    judul:     "Stockity vs Binomo vs Olymp Trade: Perbandingan Platform 2026",
    ringkasan: "Perbandingan objektif tiga platform trading populer di Indonesia — fitur, payout, deposit minimum, regulasi, dan kompatibilitas dengan robot trading otomatis.",
    kategori:  "Review",
    tanggal:   "21 Mei 2025",
    menit:     12,
  },

  // ── Artikel Baru — 7 Juni 2026 ───────────────────────────────

  {
    slug:      "cara-deposit-stockity",
    judul:     "Cara Deposit Stockity: Isi Saldo via Stockity.id untuk Trading Bot 2026",
    ringkasan: "Deposit di Stockity dilakukan di platform Stockity.id — bukan di aplikasi STC AutoTrade. Panduan akses via Webview, saldo otomatis sinkron ke bot, dan cara mulai dari akun Demo gratis.",
    kategori:  "Panduan",
    tanggal:   "7 Jun 2026",
    menit:     7,
  },
  {
    slug:      "copy-trading-stockity",
    judul:     "Copy Trading Stockity: Panduan Mode Fastrade CTC di STC AutoTrade 2026",
    ringkasan: "Fastrade CTC adalah mode copy trading di STC AutoTrade yang mirror order dari master trader secara real-time dan otomatis. Panduan cara aktivasi, setting nominal, dan tips optimasi.",
    kategori:  "Panduan",
    tanggal:   "7 Jun 2026",
    menit:     7,
  },
  {
    slug:      "minimal-deposit-stockity",
    judul:     "Minimal Order STC AutoTrade: Rp 14.000 per Trade & Simulasi Modal 2026",
    ringkasan: "Minimum nominal order di STC AutoTrade adalah Rp 14.000 per trade. Panduan simulasi modal untuk martingale 1-7 step, rekomendasi buffer aman, dan cara mulai dari akun Demo gratis.",
    kategori:  "Panduan",
    tanggal:   "7 Jun 2026",
    menit:     6,
  },
  {
    slug:      "robot-trading-pc-laptop",
    judul:     "STC AutoTrade di PC & Laptop: Akses Versi Web via stcautotradepro.id 2026",
    ringkasan: "STC AutoTrade bisa diakses di PC dan laptop via browser di stcautotradepro.id — tanpa install, semua 6 mode tersedia, fitur identik dengan APK Android.",
    kategori:  "Panduan",
    tanggal:   "7 Jun 2026",
    menit:     6,
  },
  {
    slug:      "trading-binary-option-modal-kecil",
    judul:     "Trading Binary Option Modal Kecil: Simulasi Base Rp 14K di STC AutoTrade 2026",
    ringkasan: "Simulasi konkret trading dengan modal kecil di STC AutoTrade — base order Rp 14.000, tabel martingale 1-5 step, mode yang cocok, dan fitur SL otomatis untuk proteksi saldo.",
    kategori:  "Strategi",
    tanggal:   "7 Jun 2026",
    menit:     8,
  },
  {
    slug:      "indikator-trading-binary-option",
    judul:     "Indikator di STC AutoTrade: Panduan Mode SMA, EMA, RSI 2026",
    ringkasan: "Mode Indicator di STC AutoTrade v4.4 mendukung 3 indikator: SMA, EMA, dan RSI. Panduan setting period (1-200), sensitivity, RSI overbought/oversold, dan cara kerja eksekusi otomatis.",
    kategori:  "Edukasi",
    tanggal:   "7 Jun 2026",
    menit:     9,
  },
  {
    slug:      "cara-baca-candlestick-binary-option",
    judul:     "Cara Baca Candlestick & 4 Pola Mode Momentum STC AutoTrade 2026",
    ringkasan: "Mode Momentum STC AutoTrade mendeteksi 4 pola candlestick: CandleSabit, DojiTerjepit, DojiPembatalan, dan BBSARBreak. Setiap pola bisa enable/disable secara individual.",
    kategori:  "Edukasi",
    tanggal:   "7 Jun 2026",
    menit:     9,
  },
  {
    slug:      "aset-terbaik-trading-stockity",
    judul:     "Aset Terbaik untuk Trading di Stockity: Forex, Crypto & Komoditas 2026",
    ringkasan: "Panduan memilih aset di STC AutoTrade — aset diambil real-time dari API Stockity meliputi Forex (EUR/USD, USD/IDR), Gold, Oil, dan Crypto. Tips memilih aset sesuai mode bot.",
    kategori:  "Panduan",
    tanggal:   "7 Jun 2026",
    menit:     7,
  },
  {
    slug:      "timeframe-trading-binary-option",
    judul:     "Timeframe di STC AutoTrade: Panduan Mode Fastrade & Duration Signal 2026",
    ringkasan: "Timeframe 1m-1h hanya tersedia di mode Fastrade FTT & CTC. Mode Signal pakai duration 60-300 detik. Mode AI Signal, Indicator, dan Momentum tidak punya pilihan timeframe.",
    kategori:  "Edukasi",
    tanggal:   "7 Jun 2026",
    menit:     7,
  },
  {
    slug:      "cara-menghindari-loss-stockity",
    judul:     "Cara Menghindari Loss di STC AutoTrade: SL Harian, Always Signal & Demo 2026",
    ringkasan: "Panduan manajemen risiko di STC AutoTrade — setting Stop Loss & Stop Profit harian otomatis, fitur Always Signal untuk recovery martingale, analisis History page, dan akun Demo.",
    kategori:  "Strategi",
    tanggal:   "7 Jun 2026",
    menit:     8,
  },
];
